use centroestudios;
select * from alumno where year(fecha_nacimiento)<1990;
select nombre, horas from asignatura where horas > 200 order by curso asc, nombre asc;
select nombre, horas from asignatura where curso = 1 and (ciclo="AYF" or ciclo="DAM");
select nombre, apellido, email from alumno where not email like "%gmail%";
select nombre, apellido from alumno where month(fecha_nacimiento) in (2,4,12);
select avg(nota_1Ev) from alumno_asignatura where alumno="25469874X";
select max(nota_1Ev) from alumno_asignatura where asignatura="DAM_BBDD";
select count(*) as "matriculados", count(nota_1Ev) as "1 ev", count(nota_2Ev) as "2 ev" from alumno_asignatura where asignatura = "DAM_BBDD";
select * from alumno_asignatura;
select count(*)-count(profesor) from asignatura;
use ventas; 
select * from cliente;
select * from comercial;
select * from pedido;
select * from pedido order by fecha desc;
select * from pedido order by total desc limit 2;
select distinct id_cliente from pedido where id is not null;
select * from pedido where year(fecha)=2017 and total>500;
select max(total) from pedido;
select count(categoría) from cliente;
