/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clase_1;

/**
 *
 * @author DAM
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        jLabelMensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonMensajeON = new javax.swing.JToggleButton();
        jToggleButtonMensajeOFF = new javax.swing.JToggleButton();
        jToggleButtonOFF = new javax.swing.JToggleButton();
        jToggleButtonON = new javax.swing.JToggleButton();
        jToggleButton = new javax.swing.JToggleButton();
        jToggleButtonSalir = new javax.swing.JToggleButton();
        jLabelMensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButtonMensajeON.setText("Mensaje ON");
        jToggleButtonMensajeON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonMensajeONMouseClicked(evt);
            }
        });
        jToggleButtonMensajeON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonMensajeONActionPerformed(evt);
            }
        });

        jToggleButtonMensajeOFF.setText("Mensaje OFF");
        jToggleButtonMensajeOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonMensajeOFFMouseClicked(evt);
            }
        });

        jToggleButtonOFF.setText("Botón OFF");
        jToggleButtonOFF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonOFFMouseClicked(evt);
            }
        });

        jToggleButtonON.setText("Boton ON");
        jToggleButtonON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonONMouseClicked(evt);
            }
        });

        jToggleButton.setText("Botón");
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });

        jToggleButtonSalir.setText("Salir");
        jToggleButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonSalirMouseClicked(evt);
            }
        });

        jLabelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelMensaje.setText("Este es el mensaje");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jToggleButtonMensajeOFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonOFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonMensajeON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jToggleButtonMensajeON)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonMensajeOFF)
                        .addGap(28, 28, 28)
                        .addComponent(jToggleButtonOFF))
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jToggleButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonMensajeONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonMensajeONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonMensajeONActionPerformed

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonActionPerformed
    }//GEN-LAST:event_jToggleButtonActionPerformed

    private void jToggleButtonMensajeONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonMensajeONMouseClicked
        jLabelMensaje.setVisible(true);
    }//GEN-LAST:event_jToggleButtonMensajeONMouseClicked

    private void jToggleButtonMensajeOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonMensajeOFFMouseClicked
        jLabelMensaje.setVisible(false);
    }//GEN-LAST:event_jToggleButtonMensajeOFFMouseClicked

    private void jToggleButtonOFFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonOFFMouseClicked
        jToggleButton.setEnabled(false);
    }//GEN-LAST:event_jToggleButtonOFFMouseClicked

    private void jToggleButtonONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonONMouseClicked
        jToggleButton.setEnabled(true);
    }//GEN-LAST:event_jToggleButtonONMouseClicked

    private void jToggleButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_jToggleButtonSalirMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JToggleButton jToggleButton;
    private javax.swing.JToggleButton jToggleButtonMensajeOFF;
    private javax.swing.JToggleButton jToggleButtonMensajeON;
    private javax.swing.JToggleButton jToggleButtonOFF;
    private javax.swing.JToggleButton jToggleButtonON;
    private javax.swing.JToggleButton jToggleButtonSalir;
    // End of variables declaration//GEN-END:variables
}
