/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejer_OptionPane;

import javax.swing.*;

/**
 *
 * @author DAM
 */
public class Ejer_JOptionPane extends javax.swing.JFrame {

    /**
     * Creates new form Ejer_JOptionPane
     */
    public Ejer_JOptionPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Defecto = new javax.swing.JRadioButton();
        SinIcono = new javax.swing.JRadioButton();
        WarningIcon = new javax.swing.JRadioButton();
        ErrorIcon = new javax.swing.JRadioButton();
        InformacionIcon = new javax.swing.JRadioButton();
        PreguntaIcon = new javax.swing.JRadioButton();
        jButtonMensaje = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButtonMensaje2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(Defecto);
        Defecto.setText("Mensaje e icono por defecto");

        buttonGroup1.add(SinIcono);
        SinIcono.setText("Mensaje sin icono");

        buttonGroup1.add(WarningIcon);
        WarningIcon.setText("Mensaje de Warning");

        buttonGroup1.add(ErrorIcon);
        ErrorIcon.setText("Mensaje Error");

        buttonGroup1.add(InformacionIcon);
        InformacionIcon.setText("Mensaje  de Informacion");

        buttonGroup1.add(PreguntaIcon);
        PreguntaIcon.setText("Mensaje de Pregunta");

        jButtonMensaje.setText("Mensaje");
        jButtonMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Defecto)
                    .addComponent(SinIcono)
                    .addComponent(WarningIcon)
                    .addComponent(ErrorIcon)
                    .addComponent(InformacionIcon)
                    .addComponent(PreguntaIcon)
                    .addComponent(jButtonMensaje))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Defecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SinIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WarningIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InformacionIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreguntaIcon)
                .addGap(18, 18, 18)
                .addComponent(jButtonMensaje)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simples", jPanel1);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("ShowConfinDialog con Ok/Cancel");

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("ShowConfinDialog con Yes/No");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("ShowOptionDialog con 4 opciones");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("ShowConfinDialog con Yes/No/Cancel");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("ShowInputDialog con texto");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("ShowInputDialog con lista despleglables");

        jButtonMensaje2.setText("Mensaje");
        jButtonMensaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMensaje2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jButtonMensaje2))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addGap(18, 18, 18)
                .addComponent(jButtonMensaje2)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Complejos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMensajeActionPerformed
        String mensaje = "Informacion";
        if (Defecto.isSelected()) {
            JOptionPane.showMessageDialog(null, mensaje);
        }else if (ErrorIcon.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", JOptionPane.ERROR_MESSAGE);
        }else if (InformacionIcon.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }else if (PreguntaIcon.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", JOptionPane.QUESTION_MESSAGE);
        }else if (SinIcono.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", -1);
        }else if (WarningIcon.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonMensajeActionPerformed

    private void jButtonMensaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMensaje2ActionPerformed
        String mensaje = "Informacion";
        if (jRadioButton1.isSelected()) {
            JOptionPane.showMessageDialog(null, mensaje);
        }else if (jRadioButton2.isSelected()){
            JOptionPane.showConfirmDialog(null, mensaje);
        }else if (jRadioButton3.isSelected()){
            JOptionPane.showConfirmDialog(rootPane, mensaje);
        }else if (jRadioButton4.isSelected()){
        }else if (jRadioButton5.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", JOptionPane.ERROR_MESSAGE);
        }else if (jRadioButton6.isSelected()){
            JOptionPane.showMessageDialog(null, mensaje, "INFORMACION", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonMensaje2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer_JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejer_JOptionPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Defecto;
    private javax.swing.JRadioButton ErrorIcon;
    private javax.swing.JRadioButton InformacionIcon;
    private javax.swing.JRadioButton PreguntaIcon;
    private javax.swing.JRadioButton SinIcono;
    private javax.swing.JRadioButton WarningIcon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonMensaje;
    private javax.swing.JButton jButtonMensaje2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
