/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Clase_5;

/**
 *
 * @author DAM
 */
public class Pantalla2 extends javax.swing.JDialog {
    public CalculadoraIMC_2 calculadora;
    /**
     * Creates new form Pantalla2
     */
    public void calcularyMostrar(String cadena, double altura, double peso){
        jLabelEstimado.setText(cadena);
        double imc =  peso /((altura/100)*(altura/100));
        jLabelIMC.setText("Su indice de masa corporal es: " + String.format("%.2f", imc));
        
        if (imc < 18.5) {
            jLabelComposicion.setText("Su peso es inferior al normal");
        }else if(imc >= 18.5 && imc <25){
            jLabelComposicion.setText("Su peso es normal");
        }else if(imc >= 25 && imc <30){
            jLabelComposicion.setText("Su peso es superior al normal");
        }else if(imc > 30){
            jLabelComposicion.setText("Su peso es obeso");
        }
        jLabelEstimado.setVisible(true);
        jLabelIMC.setVisible(true);
        jLabelComposicion.setVisible(true);
    }
    public Pantalla2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        calculadora = (CalculadoraIMC_2)parent;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEstimado = new javax.swing.JLabel();
        jLabelIMC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelComposicion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelEstimado.setText("Hola");

        jLabelIMC.setText("IMC = ");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelComposicion.setText("composicion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelComposicion)
                    .addComponent(jButton1)
                    .addComponent(jLabelIMC)
                    .addComponent(jLabelEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabelEstimado)
                .addGap(18, 18, 18)
                .addComponent(jLabelIMC)
                .addGap(18, 18, 18)
                .addComponent(jLabelComposicion)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calculadora.limpiarCampos();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pantalla2 dialog = new Pantalla2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelComposicion;
    private javax.swing.JLabel jLabelEstimado;
    private javax.swing.JLabel jLabelIMC;
    // End of variables declaration//GEN-END:variables
}
