/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaibislopezvara
 */
public class Ventana2 extends javax.swing.JDialog {

    public Ventana1 ventana1;
    /**
     * Creates new form Ventana2
     */
    // Creación de una nueva ventana (Ventana2) que hereda de JDialog
    public Ventana2(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);  // Llama al constructor de la clase padre (JDialog) 
        
        ventana1=(Ventana1)parent; /** Realiza un casting del componente padre (parent) 
         *                         a un objeto de tipo Ventana1 y lo almacena en 
         *                         la variable ventana1 */
        
        initComponents();       
        ventana1.OcultaLabel();
        setLocation(400,600);
    }



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVentana2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonCONTINUARV2 = new javax.swing.JButton();
        jButtonLIMPIARV2 = new javax.swing.JButton();
        jButtonATRASV2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SALUDO");

        jLabelVentana2.setText("Teclee su nombre:");

        jButtonCONTINUARV2.setText("CONTINUAR");
        jButtonCONTINUARV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCONTINUARV2ActionPerformed(evt);
            }
        });

        jButtonLIMPIARV2.setText("LIMPIAR");
        jButtonLIMPIARV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLIMPIARV2ActionPerformed(evt);
            }
        });

        jButtonATRASV2.setText("ATRÁS");
        jButtonATRASV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonATRASV2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVentana2)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonCONTINUARV2)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLIMPIARV2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonATRASV2)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelVentana2)
                .addGap(36, 36, 36)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCONTINUARV2)
                    .addComponent(jButtonLIMPIARV2)
                    .addComponent(jButtonATRASV2))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLIMPIARV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLIMPIARV2ActionPerformed
        jTextFieldNombre.setText(null);
    }//GEN-LAST:event_jButtonLIMPIARV2ActionPerformed

    private void jButtonCONTINUARV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCONTINUARV2ActionPerformed
       
        String nombre = jTextFieldNombre.getText();
        
        ventana1.EscribirNombre(nombre);
        
        this.dispose();
    }//GEN-LAST:event_jButtonCONTINUARV2ActionPerformed

    private void jButtonATRASV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonATRASV2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonATRASV2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana2 dialog = new Ventana2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonATRASV2;
    private javax.swing.JButton jButtonCONTINUARV2;
    private javax.swing.JButton jButtonLIMPIARV2;
    private javax.swing.JLabel jLabelVentana2;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
