    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaibislopezvara
 */
public class Ventana1 extends javax.swing.JFrame {

 
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.OcultaLabel();
        this.setLocationRelativeTo(null);
    }
    
    public void EscribirNombre(String nombre) {
       jLabelPulseV1.setVisible(false);
       jLabelAdiosV1.setText("Adiós "+nombre);
       jLabelAdiosV1.setVisible(true);

    }
    
    public void OcultaLabel() {
       if (jLabelAdiosV1.isVisible()) {
           jLabelAdiosV1.setVisible(false);
           jLabelPulseV1.setVisible(true);
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPulseV1 = new javax.swing.JLabel();
        jButtonCONTINUARV1 = new javax.swing.JButton();
        jButtonSALIRV1 = new javax.swing.JButton();
        jLabelAdiosV1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        jLabelPulseV1.setText("Pulse CONTINUAR para avanzar a la siguiente ventana:");

        jButtonCONTINUARV1.setText("CONTINUAR");
        jButtonCONTINUARV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCONTINUARV1ActionPerformed(evt);
            }
        });

        jButtonSALIRV1.setText("SALIR");
        jButtonSALIRV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRV1ActionPerformed(evt);
            }
        });

        jLabelAdiosV1.setText("Adiós");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPulseV1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCONTINUARV1)
                                .addGap(76, 76, 76)
                                .addComponent(jButtonSALIRV1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabelAdiosV1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelPulseV1)
                .addGap(35, 35, 35)
                .addComponent(jLabelAdiosV1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCONTINUARV1)
                    .addComponent(jButtonSALIRV1))
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSALIRV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRV1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSALIRV1ActionPerformed

    private void jButtonCONTINUARV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCONTINUARV1ActionPerformed
        Ventana2 ventana2=new Ventana2(this,true);
        ventana2.setVisible(true);
    }//GEN-LAST:event_jButtonCONTINUARV1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCONTINUARV1;
    private javax.swing.JButton jButtonSALIRV1;
    private javax.swing.JLabel jLabelAdiosV1;
    private javax.swing.JLabel jLabelPulseV1;
    // End of variables declaration//GEN-END:variables
}
